name: Chromatic
on:
  # NOTE: If you change these you must update verify_storybook-noop.yml as well
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/verify_chromatic.yml'
      - '.storybook/**'
      - 'packages/ui/src/**'
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    name: Chromatic
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1000 # Required to retrieve git history

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Install dependencies
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Build Storybook
        run: yarn build-storybook:chromatic

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # projectToken intentionally shared to allow collaborators to run Chromatic on forks
          # https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
          projectToken: chpt_dab72dc0f97d55b
          storybookBuildDir: dist-storybook
          onlyChanged: true
          externals: packages/ui/**/*.css

      - name: Post Chromatic Link in PR Comment
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## 🎨 Visual Testing Results

            Your visual changes have been tested with Chromatic! Here are the results:

            | 🔗 Link | Description |
            |---------|-------------|
            | [**Review Changes**](${{ steps.chromatic.outputs.url }}) | View visual diffs and approve/reject changes |
            | [**Build Details**](${{ steps.chromatic.outputs.buildUrl }}) | See detailed build information |
            | [**Live Storybook**](${{ steps.chromatic.outputs.storybookUrl }}) | Browse the interactive component library |

            ### 📊 Build Summary
            - **Changes detected**: ${{ steps.chromatic.outputs.changeCount }}
            - **Actual capture count**: ${{ steps.chromatic.outputs.actualCaptureCount }}

            ---

            ### 🔧 All Available Chromatic Outputs

            | Output | Value | Description |
            |--------|-------|-------------|
            | `url` | `${{ steps.chromatic.outputs.url }}` | An alias for the build URL. |
            | `buildUrl` | `${{ steps.chromatic.outputs.buildUrl }}` | The build URL. |
            | `storybookUrl` | `${{ steps.chromatic.outputs.storybookUrl }}` | The Storybook preview URL for your current branch / Pull Request. |
            | `code` | `${{ steps.chromatic.outputs.code }}` | The exit code for the current run of the Chromatic CLI. |
            | `actualCaptureCount` | `${{ steps.chromatic.outputs.actualCaptureCount }}` | The number of captured snapshots. |
            | `changeCount` | `${{ steps.chromatic.outputs.changeCount }}` | The number of tests with visual changes, including any inherited changes (e.g., due to TurboSnap). |
            | `componentCount` | `${{ steps.chromatic.outputs.componentCount }}` | The number of components in the published Storybook. |
            | `errorCount` | `${{ steps.chromatic.outputs.errorCount }}` | The number of tests with error(s), including any inherited errors (e.g., due to TurboSnap). |
            | `inheritedCaptureCount` | `${{ steps.chromatic.outputs.inheritedCaptureCount }}` | The number of inherited (not captured) snapshots (e.g., due to TurboSnap). |
            | `interactionTestFailuresCount` | `${{ steps.chromatic.outputs.interactionTestFailuresCount }}` | 	The number of stories with interaction test failures. |
            | `specCount` | `${{ steps.chromatic.outputs.specCount }}` | 	The number of stories in the published Storybook. |
            | `testCount` | `${{ steps.chromatic.outputs.testCount }}` |  The number of tests on the build. |

            ---
            *This comment is automatically updated when visual tests run.*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
