name: Chromatic
on:
  # NOTE: If you change these you must update verify_storybook-noop.yml as well
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/verify_chromatic.yml'
      - '.storybook/**'
      - 'packages/ui/src/**'
      - '**/*.stories.tsx'

jobs:
  chromatic:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]

    name: Chromatic
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Required to retrieve git history

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/ # Needed for auth

      - name: Install dependencies
        uses: backstage/actions/yarn-install@b3c1841fd69e1658ac631afafd0fb140a2309024 # v0.6.17
        with:
          cache-prefix: ${{ runner.os }}-v${{ matrix.node-version }}

      - name: Build Storybook
        run: yarn build-storybook:chromatic

      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # projectToken intentionally shared to allow collaborators to run Chromatic on forks
          # https://www.chromatic.com/docs/custom-ci-provider#run-chromatic-on-external-forks-of-open-source-projects
          projectToken: chpt_dab72dc0f97d55b
          storybookBuildDir: dist-storybook
          onlyChanged: true

      - name: Extract Chromatic Details
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url
        id: extract-details
        run: |
          # Try to extract change count from Chromatic logs
          # This is a best-effort approach as the exact log format may vary
          echo "Extracting Chromatic details from logs..."

          # Set default values
          CHANGES_COUNT="Unknown"
          STORIES_COUNT="Unknown"

          # Try to find change count in various log patterns
          if [ -f "$GITHUB_WORKSPACE/chromatic-output.log" ]; then
            CHANGES_COUNT=$(grep -oP '(\d+)\s+changes?' "$GITHUB_WORKSPACE/chromatic-output.log" | head -1 | grep -oP '\d+' || echo "Unknown")
            STORIES_COUNT=$(grep -oP '(\d+)\s+stories?' "$GITHUB_WORKSPACE/chromatic-output.log" | head -1 | grep -oP '\d+' || echo "Unknown")
          fi

          # Output the extracted values
          echo "changes-count=$CHANGES_COUNT" >> $GITHUB_OUTPUT
          echo "stories-count=$STORIES_COUNT" >> $GITHUB_OUTPUT

          echo "Changes detected: $CHANGES_COUNT"
          echo "Stories affected: $STORIES_COUNT"

      - name: Post Chromatic Link in PR Comment
        if: github.event_name == 'pull_request' && steps.chromatic.outputs.url
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## 🎨 Visual Testing Results

            Your visual changes have been tested with Chromatic! Here are the results:

            | 🔗 Link | Description |
            |---------|-------------|
            | [**Review Changes**](${{ steps.chromatic.outputs.url }}) | View visual diffs and approve/reject changes |
            | [**Build Details**](${{ steps.chromatic.outputs.buildUrl }}) | See detailed build information |
            | [**Live Storybook**](${{ steps.chromatic.outputs.storybookUrl }}) | Browse the interactive component library |

            ### 📊 Build Summary
            - **Changes detected**: ${{ steps.extract-details.outputs.changes-count }}
            - **Stories affected**: ${{ steps.extract-details.outputs.stories-count }}

            ---
            *This comment is automatically updated when visual tests run.*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
